#!/bin/bash

function resize {
	dim=(`pdfinfo "$1" | grep "Page size" | grep -Eo '[-+]?[0-9]*\.?[0-9]+'`)
	w="${dim[0]}"
	h="${dim[1]}"

	w_out=5
	h_out=`bc <<< "scale=2; $w / $h * $w_out"`

	pdfjam --outfile /tmp/final.pdf --papersize "{${h_out}in,${w_out}in}" "$1" &>/dev/null

}

pdfs=(./*_C.pdf)

resize "${pdfs[0]}"
mv /tmp/final.pdf ./final.pdf

for ((i=1;i<${#pdfs[@]};i++)); do
	resize "${pdfs[i]}"
	pdftk final.pdf /tmp/final.pdf cat output final_out.pdf &>/dev/null
	mv -f final_out.pdf final.pdf
done
