#!/bin/bash

first_f=true

for d in */ ; do
	first=true

	pdfs=( "${d}"*_C.pdf )
	(( ${#pdfs[@]} <= 1 )) && continue

	if [[ "$1" == "nd" ]]; then
		pdftk "${d}"*_C.pdf cat output "${d}/final.pdf" &>/dev/null
	else
		for pdf in "${pdfs[@]}"; do

			name=$(basename "$pdf" _C.pdf)
			# Uncomment to also redo all the toc
			tocmaker override "$pdf" -b "toc/${name}.md"
			############################################

			tocmaker wrap "$pdf" -w "$name" -o "${d}tmp.pdf"

			if $first ; then
				first=false
				mv -f "${d}tmp.pdf" "${d}final.pdf"
			else
				pdftk "${d}final.pdf" "${d}tmp.pdf" cat output "${d}tmp1.pdf" &>/dev/null
				mv -f "${d}tmp1.pdf" "${d}final.pdf"
			fi
		done

		rm -f "${d}tmp.pdf" &>/dev/null

	fi


	tocmaker wrap "${d}final.pdf" -w "${d%/}" -o tmp.pdf

	if $first_f ; then
		first_f=false
		mv -f tmp.pdf final.pdf
	else
		pdftk final.pdf tmp.pdf cat output tmp1.pdf &>/dev/null
		mv -f tmp1.pdf final.pdf

	fi
done

rm -f tmp.pdf &>/dev/null
