#!/bin/bash


function resize {
	dim=(`pdfinfo "$1" 2> /dev/null | grep "Page size" | grep -Eo '[-+]?[0-9]*\.?[0-9]+'`)

	[[ $? -eq 1 || ${#dim[@]} -ne 2 ]] && return
	w="${dim[0]}"
	h="${dim[1]}"

	if [[ $w -gt $h ]]; then
		w_out=297
		h_out=`bc <<< "scale=2; $w / $h * $w_out"`
	else
		h_out=297
		w_out=`bc <<< "scale=2; $h / $w * $h_out"`
	fi

	pdfjam --outfile "$1" --papersize "{${h_out}mm,${w_out}mm}" "$1" &>/dev/null
}

red=`tput setaf 1`
green=`tput setaf 2`
bold=`tput bold`
reset=`tput sgr0`

echo -e " ${bold}y${reset}\t\t - Confirm suggestion"
echo -e " ${bold}<Enter>${reset}\t - Ignore"
echo -e " ${bold}<Type>${reset}\t\t - Change the name to input"

path="/home/usr/repos/tocmaker/"

cp "${path}blank.pdf" "${path}preview.pdf"

(qpdfview "${path}preview.pdf" &> /dev/null &)

read -p "Press ${bold}<Enter>${reset} to continue"

for f in ./*.pdf; do
	pdf_info=`pdfinfo "$1" 2> /dev/null` | sed -n 's/^CreationDate:\(.*\)$/\1/p'`
	if [[ $? -eq 0  ]];then
		data_raw=`echo "$pdf_info" | sed -n 's/^CreationDate:\(.*\)$/\1/p'`

		date=`date -d "$date_raw" +"%Y-%m-%d"`
		if [[ $? -eq 1 ]]; then
			data_raw=`echo "$pdf_info" | sed -n 's/^ModDate:\(.*\)$/\1/p'`

			date=`date -d "$date_raw" +"%Y-%m-%d"`
		fi
	else
		date="9999-99-99"
	fi

	name=`basename "$f" .pdf`

	pdfs+=("${name}@${date}")
done


OIFS=$IFS
IFS=$'\n'
sorted=($(sort -n -t "@" -k2.1,2.4 -k2.6,2.7 -k2.9,2.10 <<<"${pdfs[*]}"))
IFS=$OIFS

for pdf in "${sorted[@]}"
do
	tmp=(${pdf//@/ })
	curr_name="${tmp[0]}"
	suggested_name="${tmp[1]}"

	/bin/cp -rf "${curr_name}.pdf" "${path}preview.pdf"

	cl_name=`echo "$curr_name" | sed -rn 's/(.*)?_C/\1/p'`


	[[ -f "../toc/${cl_name}.md" || "$curr_name" == "final" || "$curr_name" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}(_pt[0-9]+)?(_C)?$ ]] && continue

	echo -e "${bold}${red}curr:${reset}\t${curr_name}.pdf"
	echo -e "${bold}${green}sugg:${reset}\t${suggested_name}.pdf"

	resize "${curr_name}.pdf"

	read -p 'Ans: ' ans

	case $ans in

		"")
			continue
			;;

		"y")
		 	ans="$suggested_name"
		 	;;

		*)
		 	ans="$ans"
		 	;;
	esac

	mv "${curr_name}.pdf" "${ans}.pdf" &> /dev/null
done

wmctrl -lp | awk '/preview - qpdfview/{print $3}' |
xargs kill

rm "${path}preview.pdf"
