#!/bin/bash

red=`tput setaf 1`
green=`tput setaf 2`
bold=`tput bold`
reset=`tput sgr0`

for f in ./*.pdf; do
	date_in=`pdfinfo "$f" | sed -n 's/^CreationDate:\(.*\)$/\1/p'`
	suggested_name=`date -d "$date_in" +"%Y-%m-%d.pdf"`
	curr_name=`basename $f`

	[[ "$suggested_name" == "$curr_name" ]] && continue

	echo -e "${bold}${red}curr:${reset}\t${curr_name}"
	echo -e "${bold}${green}sugg:${reset}\t${suggested_name}"
	read -p 'Name (empty to confirm): ' ans
	ans="${ans}.pdf"
	[[ "$ans" == ".pdf" ]] && ans="$suggested_name"
	mv "$f" "$ans" &> /dev/null
done
