#!/bin/bash

red=`tput setaf 1`
green=`tput setaf 2`
bold=`tput bold`
reset=`tput sgr0`

echo -e " ${bold}y${reset}\t\t - Confirm suggestion"
echo -e " ${bold}<Enter>${reset}\t - Ignore"
echo -e " ${bold}<Type>${reset}\t\t - Change the name to input"

path="/home/usr/repos/tocmaker/"

cp "${path}blank.pdf" "${path}preview.pdf"

(qpdfview "${path}preview.pdf" &> /dev/null &)

read -p "Press ${bold}<Enter>${reset} to continue"

for f in ./*.pdf; do
	date_in=`pdfinfo "$f" | sed -n 's/^ModDate:\(.*\)$/\1/p'`
	date=`date -d "$date_in" +"%Y-%m-%d"`
	name=`basename "$f" .pdf`

	pdfs+=("${name}@${date}")
done


OIFS=$IFS
IFS=$'\n'
sorted=($(sort -n -t "@" -k2.1,2.4 -k2.6,2.7 -k2.9,2.10 <<<"${pdfs[*]}"))
IFS=$OIFS

for pdf in "${sorted[@]}"
do
	tmp=(${pdf//@/ })
	curr_name="${tmp[0]}"
	suggested_name="${tmp[1]}"

	/bin/cp -rf "${curr_name}.pdf" "${path}preview.pdf"

	[[ "$suggested_name" == "$curr_name" ]] && continue

	echo -e "${bold}${red}curr:${reset}\t${curr_name}.pdf"
	echo -e "${bold}${green}sugg:${reset}\t${suggested_name}.pdf"
	read -p 'Name (empty to confirm): ' ans

	case $ans in

		"")
			continue
			;;

		"y")
		 	ans="$suggested_name"
		 	;;

		*)
		 	ans="$ans"
		 	;;
	esac

	mv "${curr_name}.pdf" "${ans}.pdf" &> /dev/null
done

wmctrl -lp | awk '/preview - qpdfview/{print $3}' |
xargs kill

rm "${path}preview.pdf"
