#!/bin/bash

function resize {
	dim=(`pdfinfo "$1" 2> /dev/null | grep "Page size" | grep -Eo '[-+]?[0-9]*\.?[0-9]+'`)

	[[ $? -eq 1 || ${#dim[@]} -lt 2 ]] && return
	w="${dim[0]}"
	h="${dim[1]}"

	if (( `bc -l <<< "$w > $h"` )); then
		w_out=297
		h_out=`bc <<< "scale=2; $h / $w * $w_out"`
	else
		h_out=297
		w_out=`bc <<< "scale=2; $w / $h * $h_out"`
	fi

	pdfjam --outfile "$1" --papersize "{${w_out}mm,${h_out}mm}" "$1" &>/dev/null
}

mode="$1"
if [[ "$mode" == "a4" ]]; then
	set -- "${@:2}"
fi

for f in "$@"
do
	if [[ "$mode" == "a4" ]]; then
		pdfjam --outfile "$f" --no-landscape --paper a4paper "$f" &>/dev/null
	else
		resize "$f"
	fi
done
