#!/bin/bash

#getopts ":b" opts
#echo "$opts"
#echo "$OPTARG"
#[[ "$opts" == "b" ]] && echo "$OPTARG"
#getopts ':b:' opt
#
#[[ "$opt" == "b" ]] && echo "$OPTARG"
#arr=(./*.pdf)

arrVar+=("Dish Washer")

for value in "${arrVar[@]}"
do
     echo $value
done

#if [[ "cia" != "cia" && ! -f "./cas.md" ]]; then
#	echo "cioa"
#fi
#while getopts ":b" o; do
#    case "${o}" in
#        b)
#            b=${OPTARG}
#	    echo "$b"
#            ;;
#        *)
#            usage
#            ;;
#    esac
#done
