#!/bin/bash

[ ! -f "$1" ] && {
	echo "Non trovo il pdf"
	exit 0
}

date=`pdfdate "$1"`
if [[ $? -eq 1 ]]; then
	date="9999-99-99"
fi

path=`dirname "$1"`
name=`basename "$1" .pdf`
stats="${name: -1}"

[[ "$stats" == "C" ]] && {
	name=${name::-2}
}

ans="$name"

if [[ "$name" != "$date" && ! -f "../toc/${name}.md" ]]; then
	red=`tput setaf 1`
	green=`tput setaf 2`
	bold=`tput bold`
	reset=`tput sgr0`

	echo -e " ${bold}y${reset}\t\t - Confirm suggestion"
	echo -e " ${bold}<Enter>${reset}\t - Ignore"
	echo -e " ${bold}<Type>${reset}\t\t - Change the name to input"

	echo -e "${bold}${red}defa:${reset}\t${name}.md"
	echo -e "${bold}${green}sugg:${reset}\t${date}.md"
	read -p 'Ans: ' ans

	case $ans in

		"")
			ans="$name"
			;;

		"y")
		 	ans="$date"
		 	;;

		*)
		 	ans="$ans"
		 	;;
	esac
fi

toc_path="../toc/${ans}.md"

(qpdfview --unique --instance toc "$1" &> /dev/null &)

nvim "$toc_path" # >/dev/null 2>&1
end=`tail -n 1 "$toc_path"`

[ ! -f "$toc_path" ] && exit 0

tocmaker override "$1" -b "$toc_path"

out_path="${path}/${name}.pdf"

[[ "$end" == "end" ]] && {
	out_path="${path}/${name}_C.pdf"
}

mv "$1" "$out_path"
