#!/bin/bash

[ ! -f "$1" ] && {
	echo "Non trovo il pdf"
	exit 0
}


date_in=`pdfinfo "$1" | sed -n 's/^CreationDate:\(.*\)$/\1/p'`
toc_name=`date -d "$date_in" +"%Y-%m-%d.md"`

path=`dirname "$1"`
name=`basename "$1" .pdf`
stats="${name: -3}"

toc_path="${path}/toc/$toc_name"
#nohup st -e nvim "$toc_path" >/dev/null 2>&1 &
#nohup okular "$1" >/dev/null 2>&1 &

nvim "$toc_path" # >/dev/null 2>&1
end=`tail -n 1 "$toc_path"`

[ ! -f "$toc_path" ] && exit 0

tocmaker override "$1" -b "$toc_path"

[[ "$stats" == "pro" || "$stats" == "tok" ]] && {
	name=${name::-4}
	mv "$1" "${path}/${name}.pdf"
}

out_path="${path}/${name}_pro.pdf"

[[ "$end" == "end" ]] && {
	out_path="${path}/${name}_tok.pdf"
}

mv "${path}/${name}.pdf" "$out_path"
